repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.7.2
  hooks:
    - id: ruff
      exclude: notebooks/*
    - id: ruff-format
- repo: https://github.com/kynan/nbstripout
  rev: 0.8.0
  hooks:
    - id: nbstripout
