[project]
name = "city-mail-optimizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyterlab>=4.2.5",
    "matplotlib>=3.9.2",
    "osmnx>=1.9.4",
    "scikit-learn>=1.5.1",
]
